name: Update Dependency Graph

on:
  workflow_dispatch:
  push:
    branches:
      - dev #default branch of project

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submissions@v3
        with:
          working-directory: './'
